set nocompatible
set number
set visualbell
set ruler
set encoding=utf-8
set hidden
set ttyfast
set laststatus=2
set showmode
set showcmd

colorscheme zellner

if has("syntax")
	syntax on
endif

if has ("eval")
	filetype on
	filetype plugin on
	filetype indent on
endif
